name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to production
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Migrate DB
        run: docker compose -f docker-compose.prod.yml run --rm scraper pnpm db:migrate

      - name: Deploy
        run: docker compose -f docker-compose.prod.yml up -d --build --remove-orphans
